export enum StripePaymentMethod {
    Card = "card",
    BankAccount = "bank_account",
    Bitcoin = "bitcoin",
    Ideal = "ideal",
    SepaDebit = "sepa_debit",
    Alipay = "alipay",
    ApplePay = "apple_pay",
    GooglePay = "google_pay",
    Klarna = "klarna",
    AfterpayClearpay = "afterpay_clearpay",
    WeChatPay = "wechat_pay",
    Paypal = "paypal",
    Giropay = "giropay",
    Sofort = "sofort",
    UsBankAccount = "us_bank_account",
}
